config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :users, only: [:show]
  resources :attendings
  resources :invitees, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attending.rb
class Attending < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :attendings, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendings, source: :event_attendee
  has_many :invitees

  scope :past, -> { where('event_date < ?', Time.now) }
  scope :future, -> { where('event_date > ?', Time.now) }
end

app/models/invitee.rb
class Invitee < ApplicationRecord
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', inverse_of: 'creator'
  has_many :attendings, foreign_key: :event_attendee_id
  has_many :attended_events, through: :attendings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController

  def new
    @attending = Attending.new
  end

  def create
    @user = current_user
    @event = Event.find(params[:format])
    @attending = Attending.new(attended_event_id: @event.id, event_attendee_id: @user.id)

    if @attending.save
      flash[:notice] = "You now participate in #{@event.title} ;)"
      redirect_to @event
    else
      flash[:alert] = 'Ooops check the participation again'
      render :new, status: 422
    end
  end

  def destroy
    @user = current_user
    @event = Event.find(params[:id])
    @attending = Attending.find_by(attended_event_id: @event.id, event_attendee_id: @user.id)
    if @attending.destroy
      flash[:notice] = "You successfuly canceled your participation to #{@event.title} ;)"
      redirect_to @event
    else
      flash[:alert] = 'Event deletion went wrong :/'
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @past_events = Event.past.all
    @futur_events = Event.future.all
  end

  def new
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.created_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: 422 #unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: 422 #uprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:notice] = 'Event deletion completed'
      redirect_to :root
    else
      flash[:alert] = 'Event deletion failed'
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
    @invitees = @event.invitees
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :event_date)
  end
end

app/controllers/invitees_controller.rb
class InviteesController < ApplicationController
  def new
    @event = Event.find(params[:format])
    @invitee = Invitee.new
  end

  def create
    @invitee = Invitee.new(invitee_params)
    @event = Event.find(@invitee.event_id)

    if @invitee.save
      flash[:notice] = "Invitation send to #{@invitee.email}"
      redirect_to @event
    else
      flash[:alert] = 'Error when sending invitation'
      render :new, status: 422
    end
  end

  private

  def invitee_params
    params.require(:invitee).permit(:email, :event_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
    @attended_events = @user.attended_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendings_helper.rb
module AttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitees_helper.rb
module InviteesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br>
  <%= form.label :location %>
  <%= form.text_field :location %><br>
  <%= form.label :event_date %>
  <%= form.date_field :event_date %><br>
  <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit <%= @event.title %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>All Events</h1>

Past Events: <br>

<% @past_events.each do |pe| %>
  <% if [pe.creator, pe.attendees].flatten.include?(current_user) %>
    <%= link_to pe.title, event_path(pe) %> <br>
  <% end %>
<% end %> <br>

Upcoming Events:<br>

<% @futur_events.each do |e| %>
  <% if [e.creator, e.attendees].flatten.include?(current_user) %>
    <%= link_to e.title, event_path(e) %> <br>
  <% end %>
<% end %> <br>

<%= button_to 'Create Event', new_event_path, method: :get%>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<div class="event-details">
  Location: <%= @event.location %><br>
  Date: <%= @event.event_date %><br>
  Created By: <%= @event.creator.email %><br><br>
  <strong>Attendees:</strong><br>
  <% @attendees.each do |a| %>
    <% if a.email == current_user.email %>
      <%= link_to 'Me', user_path(a) %><br>
    <% else %>
      <%= a.email %><br>
    <% end %>
  <% end %><br>
  <strong>Invitees:</strong><br>
  <% @invitees.each do |i| %>
   <%= i.email %><br>
  <% end %>
</div><br>

<% if current_user == @event.creator %>
  <%= button_to 'Invite People', new_invitee_path(@event), method: :get %>
  <%= button_to 'Edit Event', edit_event_path(@event), method: :get%>
  <%= button_to 'Delete Event', event_path(@event), method: :delete%>
<% end %>

<% if @attendees.include?(current_user) %>
  <%= button_to 'Cancel participation', attending_path(@event), method: :delete%>
<% else %>
  <%= button_to 'Participate', attendings_path(@event)%>
<% end %>

app/views/invitees/new.html.erb
<h1>Invite People to <%= @event.title%> </h1>

<%= @test %>

<%= form_with model: @invitee do |form| %>
  <%= form.hidden_field :event_id, value: @event.id %>
  <%= form.label :email %>
  <%= form.email_field :email %>
  <%= form.submit 'Send Invite' %>
<% end %>

<%= button_to 'Back To Event', event_path(@event), method: :get%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="nav">
      <%= button_to 'Home', :root, method: :get %><br>
      <% if current_user %>
        <%= button_to 'My Events', user_path(current_user), method: :get %><br>
        <%= button_to 'Log-out', destroy_user_session_path, method: :delete %>
        <p>You are currently logged-in as: <%= current_user.email %></p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email%>'s Events</h1>

<div class="created-events">
  Created: <br><br>
  <% @created_events.each do |e| %>
    <%= link_to e.title, event_path(e) %> <br>
  <% end %>
</div><br>

<div class="attending-events">
  Attending: <br><br>
  <% @attended_events.each do |e| %>
    <% if e.event_date > Time.now %>
      <%= link_to e.title, event_path(e) %> <br>
    <% end %>
  <% end %><br><br>
  Attended:<br><br>
  <% @attended_events.each do |e| %>
    <% if e.event_date < Time.now %>
      <%= link_to e.title, event_path(e) %>
    <% end %>
  <% end %>
</div>